### ISSUE TITLE
Fix Linting

### ISSUE THREAD

**Issue by JSun14** [CornellDataScience/Ball-101#5]
Linting checks are checking yolov5 folder (which is 99% code we didn't write). Check the linting results from the merged clean-infra branch. Alot of them come from yolov5 files for example
- try and only specify linting checks maybe on the src/ folder or other util folders we have and exclude those model folders that we're bringing in

**Comment by JSun14** [comment]
no rush to do this, just making it so I don't forget. Get around to it when you feel like it tbh, doesn't have to be done within the week.

**Comment by bzhang1945** [comment]
I think Pylint also has an issue with cv2 for some reason, not picking up any members from the library (that I used in modelrunner.py)

**Comment by andrewcpp** [comment]
Yeah I am testing pylint locally right now with yolov5, I will look into this also

**Comment by andrewcpp** [comment]
Pylint should no longer pick up yolov5 as seen [here](https://github.com/CornellDataScience/Ball-101/actions/runs/4454283339)
