### ISSUE TITLE
Slow mp4 conversion

### ISSUE THREAD

**Issue by JSun14** [CornellDataScience/Ball-101#6]
Conversion between yolov5 output and streamlit compatible mp4 formats is too slow
- check if yolov5 can somehow output correct format instead
- check if streamlit can somehow accommodate yolov5s format through a diff video player or something
- other alternatives
- if all else fails, we don't support the feature to view your video on our site.

**Comment by JSun14** [comment]
take your time on this one, no need to rush or anything

**Comment by Mikonooooo** [comment]
We're no longer directly displaying Yolov5 output on streamlit. But in the very near future, we will likely create a video that visually shows our stats processing, and that will still have to go through FFMPEG transcoding because openCV doesn't come with the proper licenses.
